### ISSUE TITLE
JSON.parse with option object_class: OpenStruct

### ISSUE THREAD

**Issue by khataev** [ohler55/oj_mimic_json#4]
I guess, this [issue](https://github.com/ohler55/oj/issues/239) relates to my situation.
If I include
gem 'oj_mimic_json'
into my rails application, I could not use **JSON.parse** with **object_class: OpenStruct** option. It breakes parsing of json into **OpenStruct** and result is still a hash instead of struct object

Is there a workaround?

**Comment by ohler55** [comment]
There is support for OpenStruct with mimic. Can you provide a simple test case so I have a use case to try?

**Comment by ohler55** [comment]
Unit tests in Oj cover this. If still a problem open an issue on Oj. Thanks.
